version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - 6333:6333
      - 8000:8000

    volumes:
      - .:/code 
 
    develop:
      watch:
        - path: .
          action: rebuild

    deploy:
      resources:
        limits:
          memory: 4096M  # Adjust the memory limit as needed
